#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

EXTPLORER_POOL_CONF="/etc/php5/fpm/pool.d/openmediavault-extplorer-site.conf"
EXTPLORER_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-extplorer-site.conf"

case "$1" in
    purge|remove)
        rm -rf /usr/share/extplorer

        if [ -e "${EXTPLORER_SITE_CONF}" ]; then
            rm ${EXTPLORER_SITE_CONF}
        fi

        if [ -e "${EXTPLORER_POOL_CONF}" ]; then
            rm ${EXTPLORER_POOL_CONF}
        fi

        userdel -r extplorer

        service php5-fpm reload
        service nginx reload
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
