#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

FILENAME="eXtplorer_2.1.5.zip"
LINK="http://downloads.sourceforge.net/project/extplorer/${FILENAME}"
FILE="/tmp/${FILENAME}"
INSTALL_DIR="/usr/share/extplorer"
CONFIG_FILE="${INSTALL_DIR}/config/.htusers.php"
SCRIPTS_FILE="scripts.tar.gz"

USERNAME="extplorer"

case "$1" in
    configure)

        if ! getent passwd ${USERNAME} >/dev/null 2>&1; then
            echo "Adding ${USERNAME} user..."
            useradd --create-home --groups users --no-user-group --shell /usr/sbin/nologin ${USERNAME}
        else
            echo "${USERNAME} user already exists."
        fi

        if [ ! -d "${INSTALL_DIR}" ]; then
            echo "Installing eXtplorer..."

            mkdir -p ${INSTALL_DIR}

            if [ -f "${FILE}" ]; then
                rm -f ${FILE}
            fi

            wget ${LINK} -O ${FILE}
            unzip ${FILE} -d ${INSTALL_DIR}
            rm -f ${FILE}

            tar xzf "${INSTALL_DIR}/${SCRIPTS_FILE}" -C ${INSTALL_DIR}

            cat <<EOF > ${CONFIG_FILE}
<?php
    // ensure this file is being included by a parent file
    if( !defined( '_JEXEC' ) && !defined( '_VALID_MOS' ) ) die( 'Restricted access' );
    \$GLOBALS["users"]=array(
        array('admin','\$2a\$08\$o9113Sa234xV8aGmC2mZvepUeYyPsUU5jibk3FxwP7nE7zTQ/S0Ha','/','http://localhost','1','','7',1),
    );
?>
EOF

            chown -R openmediavault:openmediavault ${INSTALL_DIR}
        else
            echo "eXtplorer already installed."
        fi

        omv-mkconf php5fpm
        service php5-fpm reload

        omv-mkconf nginx
        service nginx reload

        echo "Default username is:  admin"
        echo "Default password is:  openmediavault"

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
